### ISSUE TITLE
Misalignment of x-axis when combining gg_genetracks with another ggplot.

### ISSUE THREAD

**Issue by VitorAguiar** [myles-lewis/locuszoomr#21]
Hi,

I tried combining a gg_genetracks with another ggplot with patchwork, and the x axes don't align well.

![susie_tnfaip3](https://github.com/myles-lewis/locuszoomr/assets/3875539/06b3d937-a99d-4dc1-9aa3-7ee3a9d74bf7)

Then, I tried forcing the x-axis range for gg_genetracks with:

```
gg_genetracks(loc) + coord_cartesian(xlim = range(loc$data$pos)) + scale_x_continuous(labels = function(x) x/1e6)
```

Now the axis labels align well, but genes are kept on original positions, so the plot is wrong.

![susie_tnfaip3-2](https://github.com/myles-lewis/locuszoomr/assets/3875539/820b1ceb-091a-4d20-a3a1-8ff39c73d0f4)

I'd appreciate any help, thank you!

**Comment by myles-lewis** [comment]
Hi Vitor,

You need to post the code you used to generate the top ggplot2 scatter plot as you have modified the legend and its position as well as axes (looks like a different ggplot2 theme), as well as the code you use to call patchwork. Without this I can't see what has caused patchwork to fail and so I would be unlikely to be able to help you much. It would be even better and more helpful if you could post a reprex (reproducible example) please, perhaps using the example data included in the package. What system/OS are you on; what version of R and what version of locuszoomr, ggplot2, patchwork etc? Are you using RStudio or standard R? Have you updated all packages to the latest versions?

Have you tried using cowplot::plot_grid() instead? I find this more stable as patchwork has to do quite a lot of work to reduce plots to objects and use symbols to link them.

The reason modifying the gg_genetracks alters the axis but not the gene track graphics is that the gene track graphics is a single grob generated using the grid package. The gg_genetracks axis needs to be left alone so that it aligns with the grob. You will have better luck modifying the alignment of the scatter plot. My guess is that the misalignment is caused because of the legend.

Bw,
Myles

**Comment by myles-lewis** [comment]
Example code:

```
library(EnsDb.Hsapiens.v75)
library(locuszoomr)
library(patchwork)
library(ggplot2)

data(SLE_gwas_sub)
loc <- locus(SLE_gwas_sub, gene = 'UBE2L3', flank = 1e5, LD = "r2",
             ens_db = "EnsDb.Hsapiens.v75")

p <- gg_scatter(loc)
g <- gg_genetracks(loc)

# this works: correct alignment
p / g

# move legend to outside the scatter plot
p2 <- p + theme(legend.position = "right")

# this also works: correct alignment
p2 / g
```

**Comment by VitorAguiar** [comment]
@myles-lewis Thanks for your suggestions. I got a fresh R v4.4.0 install and reinstalled all packages. 

After further investigation, it seems to me that the issue is caused when `flank` value specified in `locus()` leads to a region wider than the GWAS data available. For example, in the code below, I reduce `SLE_gwas_sub` to a region of ±100kb around the TSS, then I use flank = 200,000Kb in `locus()`.

`gg_scatter()` takes care of that, but creating the `p` plot with custom ggplot2 code does not.
 

I am using R v4.4.0 on Rocky8 linux, standard R (not Rstudio), saving plots with ggsave. Package versions:

- ggplot2 v3.5.1
- EnsDb.Hsapiens.v75 v2.99.0
- locuszoomr v0.3.0
- patchwork v1.2.0


```
library(ggplot2)
library(EnsDb.Hsapiens.v75)
library(locuszoomr)
library(patchwork)

data(SLE_gwas_sub)

tss <- 21903736

SLE_gwas_sub2 <- 
    SLE_gwas_sub |>
    dplyr::filter(pos >= tss - 1e5, pos <= tss + 1e5)

loc <- locus(SLE_gwas_sub, 
	     gene = 'UBE2L3', 
	     flank = 2e5,
	     LD = "r2",
             ens_db = "EnsDb.Hsapiens.v75")

p <-
    ggplot(data = SLE_gwas_sub2) +
    geom_point(aes(x = pos, y = -log10(p))) +
    scale_x_continuous(limits = range(loc$data$pos),
		       labels = function(x) x/1e6L) +
    theme_classic() +
    labs(x = NULL)

g <- gg_genetracks(loc)

ggsave("./plots/reprex.png", p / g, height = 5)
```

**Comment by VitorAguiar** [comment]
@myles-lewis Thanks for your suggestions. I have just deleted my last comment, and will continue investigating this tomorrow.

**Comment by myles-lewis** [comment]
Hi Vitor,

I did see you last comment before you deleted it. I think what you want to do is manually change the x axis limit rather than specify it using `flank`, so that you use the actual range of the points at that region. The way to do this is first to define the `locus` object.  Then to manually alter the `xrange` element in it. Then call both `gg_scatter` and `gg_genetracks`. For alignment these commands rely on the x axis range as stored in `loc$xrange`. You can manually alter the x axis limits in `gg_genetracks`, but this is not a good idea as the grob of the genes won't update.

Here is an example of how to do this which maintains alignment and fixes the gene tracks themselves.

```
library(EnsDb.Hsapiens.v75)
library(locuszoomr)
library(patchwork)
library(ggplot2)

data(SLE_gwas_sub)
loc <- locus(SLE_gwas_sub, gene = 'UBE2L3', flank = 8e4, LD = "r2",
             ens_db = "EnsDb.Hsapiens.v75")

p <- gg_scatter(loc) + theme(legend.position = "right")
g <- gg_genetracks(loc)

# this also works: correct alignment
# but there is a gap on left hand side, caused by a region with no actual SNPs 
# on the left side of UBE2L3
p / g

# solution
loc$xrange <- range(loc$data$pos)
p <- gg_scatter(loc) + theme(legend.position = "right")
g <- gg_genetracks(loc)

p / g
```

Is this what you wanted?

Myles

**Comment by VitorAguiar** [comment]
@myles-lewis I will conduct further testing, but using

```
+ scale_x_continuous(limits = loc$xrange)
```

to build the `p` plot with custom ggplot2 code does seem to fix the issue.

Thank you so much!
