### ISSUE TITLE
Can non-modal species use locuszoomr

### ISSUE THREAD

**Issue by yunmika** [myles-lewis/locuszoomr#24]
Thanks for the work you've done on locuszoomr, it's been very helpful, but I was wondering if it could be applied to non-modal species?

**Comment by yunmika** [comment]
I'm trying to build the ens_db, but every time it fails at this step, so I'm trying to understand if I have to use the ens_db with the species already built in order to use locuszoomr?

**Comment by myles-lewis** [comment]
Hi Fuchuan Han,

Yes locuszoomr should work with non-model species but you must have a functional ensembldb object for the package to work. I’ve not generated a fresh ensembldb object myself so I can’t really help with that process. Have you checked AnnotationHub, to see if your species of interest already had a genome reference db available?

Bw,
Myles

On 24 Jul 2024, at 17:44, Fuchuan Han ***@***.***> wrote:

﻿

I'm trying to build the ens_db, but every time it fails at this step, so I'm trying to understand if I have to use the ens_db with the species already built in order to use locuszoomr?

**Comment by yunmika** [comment]
Thank you for your reply. I did stop at the step of building ens_db, which is more demanding on the gff file. This should be the main reason that prevents the use of locuszoomr without ens_db species. I will make some other attempts.
